@abstract
class_name Config

const CARD_COUNT := 5

const CARD_DECK_PULL_WAIT_TIME := 2.0

const GAME_TIMER_ROUND_DURATION: float = 120.0
const GAME_TIMER_USE_DURATION: float = 5.0

const HAND_CARD_DRAW_INTERVAL := 0.25

const STUFF_PILE_MIN := 100.0
const STUFF_PILE_MAX := 1000.0

const BASE_DUDE_SPAWN_COST := 10.0
const BASE_DUDE_SPAWN_TIME := 5.0

const DUDE_SPEED := 0.5
const DUDE_COLLECTION_RATE := 5.0
const DUDE_COLLECTION_CAPACITY := 15.0

const PLAYER_TEAM := 0
